# Generated by Django 3.1.1 on 2020-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, db_column='category_name', help_text='Type of category', max_length=30, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='Auto incremental unique interger values.', primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(db_column='title', help_text='Title of content data', max_length=30, verbose_name='Title')),
                ('body', models.CharField(db_column='body', help_text='Body of data', max_length=300, verbose_name='Body')),
                ('summary', models.CharField(db_column='summary', help_text='Summary Information', max_length=60, verbose_name='Summary')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', help_text='Date on which the record was inserted. This is by default values and will be updated using python function save.', verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now_add=True, db_column='update_date', help_text='Date on which the record was updated. This is by default values and will be updated using python function save.', verbose_name='Update Date')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='This column is used for soft delete. Users can reactivate the entry via portal', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False, help_text='This column is used for hard delete. Users cannot reactivate the entry via portal', verbose_name='Is Delete')),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'content',
            },
        ),
    ]
