# Generated by Django 3.1.1 on 2020-09-17 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(db_column='phone', default=10, help_text='Phone number of user', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.PositiveIntegerField(db_column='pincode', default=6, help_text='Area Pincode', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Pincode'),
        ),
    ]
