# Generated by Django 3.1.1 on 2020-09-17 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200917_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(db_column='phone', help_text='Phone number of user', validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Only alphanumeric characters are allowed.')], verbose_name='Phone Number'),
        ),
    ]
